algoritmo "funcaoSomaParametro"
//Disciplina: Logica de Programacao
//Faculdade: Descomplica
//Data: 18/11/24
funcao mult (x, y: inteiro): inteiro //variaveis locais
inicio
   retorne x * y
fimfuncao

var
   //variaveis globais
   n,m: inteiro
inicio //aqui se inicia o programa principal
   //entrada de dados
   escreva("Digite Num_1: ")
   leia(n)
   escreva("Digite Num_2: ")
   leia(m)
   //imprime na tela
   escreva("O resultado é: ",mult(n,m):4:0)



fimalgoritmo